version: '3.3'
services:
  db:
    image: mysql:5.7
    #restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: 'America/Sao_Paulo'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ~/.MySQLDBData/mysqlonly/mysql_knex/lib/mysql
volumes:
  my-db: